package com.smoothstack.lms.menu;

public enum  MenusEnum {
    MAIN,
    MAIN_LIBRARIAN,
    BRANCHES_SELECTOR,
    LIBRARIAN_OPTIONS,
    UPDATE_BRANCH,
    LIBRARIAN_BOOK_PICKER,
    BORROWER_BOOK_PICKER,
    ADMIN_MAIN,
    ADMIN_BOOK_MAIN,
    ADMIN_BOOK_ADD,
    ADMIN_BOOK_UPDATE,
    ADMIN_BOOK_UPDATE_OPTIONS,
    ADMIN_BOOK_DELETE,
    ADMIN_GENRES_MAIN,
    ADMIN_PUB_MAIN,
    ADMIN_PUB_UPDATE_OPTIONS,
    ADMIN_LB_MAIN,
    ADMIN_BORROWER_MAIN,
    ADMIN_BORROWER_UPDATE_OPTIONS,
    LB_UPDATE,
    BORROWER_MAIN
}
